services:
  - type: web
    name: healthassist-api
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn healthAssit.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: healthassist-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: healthassist-api.onrender.com

databases:
  - name: healthassist-db
    databaseName: healthassist_db
    user: healthassist_db_user
